### ISSUE TITLE
build failed : Invalid regular expression

### ISSUE THREAD

**Issue by OElabs-official** [vala-lang/vala-language-server#283] opened 2023-02-16 18:57 UTC
0.48.5
archlinux / aarch64 /

../src/documentation/girdocumentation.vala:326.29-326.57: error: Invalid regular expression //!\[(.*?)\]\(([~:\/\\\w-.]+)\)'. 326 |             comment_data = /!\[(.*?)\]\(([~:\/\\\w-.]+)\)/ |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ../src/documentation/girdocumentation.vala:355.29-355.51: error: Invalid regular expression //[(.?)][([\w-\s]+)]'.
355 | comment_data = /[(.?)][([\w-\s]+)]/
| ^~~~~~~~~~~~~~~~~~~~~~~
../src/documentation/doccomment.vala:132.17-132.59: error: Invalid regular expression `//([[|{{)([:/\\w-.]+)(|(.*?))?(]]|}})'.
132 | body = /([[|{{)([:/\\w-.]+)(|(.*?))?(]]|}})/
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Compilation failed: 3 error(s), 0 warning(s)

anyway fix this?

**Comment by KirMozor** [comment] 2023-02-19 08:10
Same error :(

**Comment by benwaffle** [comment] 2023-02-21 11:20
This is fixed in master. @Prince781 can you tag a new build?

**Comment by benwaffle** [comment] 2023-02-21 11:21
duplicate of #263

**Comment by benwaffle** [comment] 2023-02-24 06:32
@OElabs-official please try version 0.48.7 in the AUR

**Closed** 2023-02-24 06:34 UTC
